# Generated by Django 4.0.5 on 2022-06-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner_img',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.TextField(default=None)),
            ],
        ),
    ]
