# Generated by Django 4.0.5 on 2022-07-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_ecommerce', '0002_banner_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner_img',
            name='desc',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
