# Generated by Django 4.0.5 on 2022-07-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_ecommerce', '0003_banner_img_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
